cj-hg2git: explain where to get dependency from; oh,
actually *was* named with the same name. Sigh.

diff --git a/cj-hg2git b/cj-hg2git
--- a/cj-hg2git
+++ b/cj-hg2git
@@ -15,8 +15,15 @@ fi
 source="$(chase "$1")"
 target="$2"
 
-set -x
-git init "$target"
-cd "$target"
-hg-fast-export -r "$source"
-#git reset --hard
+(
+    set -eu
+    set -x
+    git init "$target"
+    cd "$target"
+    hg-fast-export -r "$source"
+    #git reset --hard
+) || (
+    echo "failed: if hg-fast-export is missing, you need to:"
+    echo "  apt install hg-fast-export"
+    false
+)
