finally correct
(well with regards to my testing)

Have to differentiate the kinds of error exit codes that grep returns.

diff --git a/is-clock-correct b/is-clock-correct
--- a/is-clock-correct
+++ b/is-clock-correct
@@ -38,8 +38,15 @@ possibly_echo () {
     fi
 }
 
+# I hope I'm cutting at the right places?
+
+assert_datepart () {
+    echo "$1" | perl -wne '/^[A-Z][a-z]{2,3} +\d+ *$/ or die "'"`printf '%q' "$0"`"': invalid cut-out?: $_"'
+}
 
 curday="`date|cut -c5-11`"
+
+assert_datepart "$curday"
 
 tmpfile1="`tempfile`"
 trap 'rm "$tmpfile1"' EXIT
@@ -48,18 +55,9 @@ grep 'ntpd.*adjusting local clock by' /var/log/daemon.log|tail -1|cut -c1-7 > "$
 remember=("${PIPESTATUS[@]}")
 test "${remember[2]}" -eq 0
 test "${remember[1]}" -eq 0
-test "${remember[0]}" -eq 0
-lastlogentry="`cat "$tmpfile1"`"
 
-# I hope I'm cutting at the right places?
-
-assert_datepart () {
-    echo "$1" | perl -wne '/^[A-Z][a-z]{2,3} +\d+ *$/ or die "'"`printf '%q' "$0"`"': invalid cut-out?: $_"'
-}
-
-assert_datepart "$curday"
-
-if [ -n "$lastlogentry" ]; then
+if test "${remember[0]}" -eq 0; then
+    lastlogentry="`cat "$tmpfile1"`"
     assert_datepart "$lastlogentry"
 
     if [ "$curday" = "$lastlogentry" ]; then
@@ -71,6 +69,11 @@ if [ -n "$lastlogentry" ]; then
 	exit 0
     fi
 else
-    possibly_echo "yes"
-    exit 0
+    # missing matches are accepted
+    if test "${remember[0]}" -eq 1; then
+	possibly_echo "yes"
+	exit 0
+    else
+	exit 1
+    fi
 fi
