really fix netcat usage
Turns out ubuntu has nc.openbsd by default and that was what broke my
script, but worse than that, there's no common set of options to make
it work, impressive.

diff --git a/netfetch b/netfetch
--- a/netfetch
+++ b/netfetch
@@ -19,6 +19,30 @@ fi
 SERVER="$1"
 PORT="$2"
 
+
+# Netcat is an utterly broken API: traditional netcat and nc.openbsd
+# don't share a common set of options to work correctly as a client
+# that copies all data from the server regardless of its own stdin,
+# thus need to differentiate this way:
+
+have () {
+    which "$1" > /dev/null
+}
+
+if have nc.traditional; then
+    NETCAT_CLIENT="nc.traditional"
+elif have nc.openbsd; then
+    # nc.openbsd neither works without -q option nor supports -q-1,
+    # nor does -q0 mean infinite, thus need to use a big enough number
+    # of seconds
+    NETCAT_CLIENT="nc.openbsd -q999999999"
+else
+    echo "can't find either nc.traditional or nc.openbsd" >&2
+    exit 1
+fi
+
+
+
 # pw needs to be on stdin, tty won't work because the parent shell
 # would over-read from it.
 
@@ -28,7 +52,7 @@ PORT="$2"
 # with file descriptors Bash uses internally."
 
 {
-netcat -q999999999 "$SERVER" "$PORT" < /dev/null \
+$NETCAT_CLIENT "$SERVER" "$PORT" < /dev/null \
     | gpg -q -d --batch --passphrase-fd 9 \
     | tar x ${z}-f -
 } 9<&0
