netsend: fixes

diff --git a/netsend b/netsend
--- a/netsend
+++ b/netsend
@@ -11,6 +11,11 @@ usage() {
     exit 1
 }
 
+die () {
+    echo "$myname: $@"
+    exit 1
+}
+
 if [[ $# -lt 1 || $1 = "-h" || $1 = "--help" ]]; then
     usage
 fi
@@ -22,20 +27,19 @@ echo "Please paste the line that says 'NETSEND' from netreceive's output:"
 IFS=" " read token pass zz ip port
 
 if ! [ "$token" = NETSEND ]; then
-    echo "$myname: error: did not get a line that starts with NETSEND."
-    exit 1
+    die "error: did not get a line that starts with NETSEND."
 fi
 
 ##echo "token=$token, pass=$pass, zz=$zz, ip=$ip, port=$port"
 
 if [ "$zz" = "-z" ]; then
-    z="-z "
+    z="-z"
 elif [ "$zz" = "-Z" ]; then
-    z=""
+    z="-Z"
 elif [ "$zz" = "-l" ]; then
     z="--lzop"
 else
-    echo "$myname: error: did get unknown flag '$zz' instead of -z|-Z|-l."
+    die "error: did get unknown flag '$zz' instead of -z|-Z|-l."
 fi
 
 
