newbash: remove the 'remember' comment
OK?

diff --git a/newbash b/newbash
--- a/newbash
+++ b/newbash
@@ -4,7 +4,7 @@ if [ $# -eq 1 ]; then
     if test -f "$1"; then
 	echo "File $1 existiert bereits!" >&2
     else
-	echo -n -e '#!/bin/bash\n\nset -euo pipefail\nIFS=\n# remember, *still* need to quote variables!\n\n'> "$1"
+	echo -n -e '#!/bin/bash\n\nset -euo pipefail\nIFS=\n\n'> "$1"
 	if [ "$EDITOR" = "nc" ]; then
 	    echo >> "$1"   # nedit overwrites the selected line upon typing
 	fi
