scoma: add -f option

diff --git a/scoma b/scoma
--- a/scoma
+++ b/scoma
@@ -6,34 +6,58 @@
 set -eu
 
 usage () {
-    echo "$0 [ -m message | -c commit ]"
-    echo "  add all, metadata save, commit and push."
+    echo "$0 [ -m message | -c commit ] [ -f ]"
+    echo "  Add all, run cj-gitmetadata save, commit and push."
     echo "  Note: set up push upstream so that 'git push'"
     echo "  without arguments works."
+    echo
+    echo "  Options:"
+    echo "    -f      run from root of working directory even if not there"
+    echo "    -m, -c  passed to git commit"
     exit 1
 }
 
-if [ $# -eq 0 ]; then
-    options="-m ."
-elif [ $# -eq 2 ]; then
-    if [[ $1 = "-m" || "$1" = "-c" ]]; then
-	options="$1 $(printf '%q' "$2")"
+opt_force=0
+options=""
+seen_m_or_c=0
+
+while [ $# -ne 0 ]; do
+    if [[ $1 = "-f" ]]; then
+        opt_force=1
+        shift
     else
-	usage
+        if [[ $1 = "-m" || "$1" = "-c" ]]; then
+	    if [ $# -ge 2 ]; then
+                options="$options $1 $(printf '%q' "$2")"
+                seen_m_or_c=1
+                shift
+                shift
+            else
+                usage
+            fi
+        else
+	    usage
+        fi
     fi
-else
-    usage
+done
+
+if [[ $seen_m_or_c = 0 ]]; then
+    options="$options -m ."
 fi
 
 
 a=`git rev-parse --show-toplevel`
 b=`pwd -P`
 if [ "$a" != "$b" ]; then
-    a=$(chase "$a")
-    b=$(chase "$b")
-    if [ "$a" != "$b" ]; then
-	echo "not in root of git working directory, aborting"
-	exit 1
+    if [[ $opt_force = 1 ]]; then
+        cd "$a"
+    else
+        a=$(chase "$a")
+        b=$(chase "$b")
+        if [ "$a" != "$b" ]; then
+	    echo "not in root of git working directory and -f not given, aborting"
+	    exit 1
+        fi
     fi
 fi
 
