spull: implement -a as well

diff --git a/spull b/spull
--- a/spull
+++ b/spull
@@ -1,7 +1,43 @@
 #!/bin/bash
 
-set -eux
+set -eu
 
+usage () {
+    echo "$0 [ -a ]"
+    echo "  git pull, and run cj-gitmetadata restore."
+    echo
+    echo "  Options:"
+    echo "    -a      cd to root of working directory when not there"
+    exit 1
+}
+
+opt_all=0
+
+while [ $# -ne 0 ]; do
+    if [[ $1 = "-a" ]]; then
+        opt_all=1
+        shift
+    else
+	usage
+    fi
+done
+
+a=`git rev-parse --show-toplevel`
+b=`pwd -P`
+if [ "$a" != "$b" ]; then
+    if [[ $opt_all = 1 ]]; then
+        cd "$a"
+    else
+        a=$(chase "$a")
+        b=$(chase "$b")
+        if [ "$a" != "$b" ]; then
+	    echo "not in root of git working directory and -a not given, aborting"
+	    exit 1
+        fi
+    fi
+fi
+
+set -x
 
 if git status |grep '^nothing to commit' -q; then
 
